language: node_js
node_js:
  - "14.16.1"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.80
before_script:
  - npm install -g bower
  - bower install
